# Generated by Django 5.1.3 on 2024-11-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
