# Generated by Django 5.1.3 on 2024-11-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='email',
            new_name='subscription_email',
        ),
    ]
